# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

div_data <- function(D) {
    .Call(`_RSMOTE_div_data`, D)
}

KNN_P <- function(P, D, k, type_maj) {
    .Call(`_RSMOTE_KNN_P`, P, D, k, type_maj)
}

remove_noise <- function(n_maj, k, P) {
    .Call(`_RSMOTE_remove_noise`, n_maj, k, P)
}

absolute_density <- function(P, Neigh, k, self = TRUE) {
    .Call(`_RSMOTE_absolute_density`, P, Neigh, k, self)
}

relative_dentisy <- function(P, N, k) {
    .Call(`_RSMOTE_relative_dentisy`, P, N, k)
}

KNN <- function(P, D, k) {
    .Call(`_RSMOTE_KNN`, P, D, k)
}

clusterRD <- function(RD) {
    .Call(`_RSMOTE_clusterRD`, RD)
}

over_sampling <- function(N, k, pureP, RD_clusters, nnarray, num_maj) {
    .Call(`_RSMOTE_over_sampling`, N, k, pureP, RD_clusters, nnarray, num_maj)
}

